---
name: On Master

on:
  push:
    tags: ['v*']
    branches: ['master']

jobs:
  buildLintTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Build, lint and test
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test

      - uses: actions/upload-artifact@master
        if: ${{ matrix.node == '16' }}
        with:
          name: build artifacts
          path: dist/

  publishVersion:
    runs-on: ubuntu-latest
    needs: buildLintTest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/download-artifact@master
        with:
          name: build artifacts
          path: dist

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
